name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.python-version }}-${{ matrix.pydantic-version }}
      cancel-in-progress: true
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        pydantic-version: [pydantic-v1, pydantic-v2]
    env:
      # OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      PYDANTIC_VERSION: ${{ matrix.pydantic-version }}

    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          version: "latest"

      - name: Install Dependencies for test group
        run: uv sync --no-dev --group ${{ matrix.pydantic-version }}

      - name: Run Pytest
        run: uv run poe test

      - name: Upload test results
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: PYTHON_VERSION,PYDANTIC_VERSION

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: PYTHON_VERSION,PYDANTIC_VERSION